[workspace]

members = [
  "eaf",  # parsing and manipulation of EAF transcripts
  "db",   # sqlite db
  # "fs",   # file-system store for transcripts (git) and recordings
  # "cli",  # command line interface
  "web",  # web interface
]
